language: android

jdk:
  - oraclejdk8

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=8
  matrix:
    - ANDROID_TARGET=android-24
    - ANDROID_TARGET=android-23
    - ANDROID_TARGET=android-22
    - ANDROID_TARGET=android-21
    - ANDROID_TARGET=android-19

matrix:
  allow_failures:
    - env: ANDROID_TARGET=android-24
    - env: ANDROID_TARGET=android-23
    - env: ANDROID_TARGET=android-22

install:
  # SDK
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-24.0.3
  - echo y | android update sdk -u -a -t android-24
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
  # Emulator
  - echo y | android update sdk -u -a -t $ANDROID_TARGET
  - echo y | android update sdk -u -a -t sys-img-armeabi-v7a-$ANDROID_TARGET

before_script:
  # Setup emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi armeabi-v7a --sdcard 200M
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 30
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean testDebug connectedDebugAndroidTest jacocoDebugReport coveralls -Pci -Dscan --stacktrace

sudo: required

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
